# -*- coding: utf-8 -*-
"""
ThermalAnalysis GUI サブパッケージ。
全 Qt ダイアログ・タスクパネル・FreeCAD コマンドクラスをここから import できる。
"""

from ThermalAnalysis.gui.commands import (
    ThermalAnalysis_Modeling_PrepareModel,
    ThermalAnalysis_Modeling_Defeaturing,
    ThermalAnalysis_Modeling_DefeaturingSelected,
    ThermalAnalysis_Modeling_EditProperties,
    ThermalAnalysis_Modeling_BulkSetProperties,
    ThermalAnalysis_Modeling_ManageMaterials,
    ThermalAnalysis_Modeling_VisualizeActiveSide,
    ThermalAnalysis_Modeling_VisualizeAbsorptivity,
    ThermalAnalysis_Modeling_VisualizeEmissivity,
    ThermalAnalysis_Modeling_VisualizeTransmittance,
    ThermalAnalysis_Modeling_RestoreDefaultDisplay,
    ThermalAnalysis_Modeling_DisplayOptions,
    ThermalAnalysis_DisplayParametersSettings,
    ThermalAnalysis_ToggleHoverLabel,
    ThermalAnalysis_Modeling_CalculateThermalMass,
    ThermalAnalysis_Modeling_CalculateConductance,
    ThermalAnalysis_Modeling_CalculateRadiationConductance,
    ThermalAnalysis_Modeling_AddConductance,
    ThermalAnalysis_Modeling_ThermalModelExport,
    ThermalAnalysis_Modeling_SubdivideSurface,
    ThermalAnalysis_Post_PostProcessing,
    ThermalAnalysis_Orbit_CalcHeatAndVisualize,
    ThermalAnalysis_Orbit_SaveHeatArrayCSV,
    ThermalAnalysis_Orbit_ExportHeatArrayOnly,
    ThermalAnalysis_Orbit_ClearVisualization,
    ThermalAnalysis_Orbit_StepOrbitFrames,
    ThermalAnalysis_Orbit_ApplyOrbitHeatToRadiation,
    _LegacyRadiationCommandAlias,
)
from ThermalAnalysis.gui.panels import (
    EditPropertiesTaskPanel,
    BulkPropertiesDialog,
    MaterialEditorDialog,
    PrepareModelDialog,
    DefeaturingDialog,
    DisplayOptionsDialog,
    DisplayParametersSettingsDialog,
    RadiationParamsDialog,
    ThermalModelExportDialog,
    PostProcessingDialog,
    SubdivideSurfaceDialog,
)
from ThermalAnalysis.gui.orbit_gui import (
    OrbitEnvironmentDialog,
    load_tle_presets,
    save_tle_presets,
)
from ThermalAnalysis.gui.orbit_step_dialog import OrbitStepDialog

__all__ = [
    # コマンドクラス
    "ThermalAnalysis_Modeling_PrepareModel",
    "ThermalAnalysis_Modeling_Defeaturing",
    "ThermalAnalysis_Modeling_DefeaturingSelected",
    "ThermalAnalysis_Modeling_EditProperties",
    "ThermalAnalysis_Modeling_BulkSetProperties",
    "ThermalAnalysis_Modeling_ManageMaterials",
    "ThermalAnalysis_Modeling_VisualizeActiveSide",
    "ThermalAnalysis_Modeling_VisualizeAbsorptivity",
    "ThermalAnalysis_Modeling_VisualizeEmissivity",
    "ThermalAnalysis_Modeling_VisualizeTransmittance",
    "ThermalAnalysis_Modeling_RestoreDefaultDisplay",
    "ThermalAnalysis_Modeling_DisplayOptions",
    "ThermalAnalysis_DisplayParametersSettings",
    "ThermalAnalysis_ToggleHoverLabel",
    "ThermalAnalysis_Modeling_CalculateThermalMass",
    "ThermalAnalysis_Modeling_CalculateConductance",
    "ThermalAnalysis_Modeling_CalculateRadiationConductance",
    "ThermalAnalysis_Modeling_AddConductance",
    "ThermalAnalysis_Modeling_ThermalModelExport",
    "ThermalAnalysis_Modeling_SubdivideSurface",
    "ThermalAnalysis_Post_PostProcessing",
    "ThermalAnalysis_Orbit_CalcHeatAndVisualize",
    "ThermalAnalysis_Orbit_SaveHeatArrayCSV",
    "ThermalAnalysis_Orbit_ExportHeatArrayOnly",
    "ThermalAnalysis_Orbit_ClearVisualization",
    "ThermalAnalysis_Orbit_StepOrbitFrames",
    "ThermalAnalysis_Orbit_ApplyOrbitHeatToRadiation",
    # ダイアログ・パネル
    "EditPropertiesTaskPanel",
    "BulkPropertiesDialog",
    "MaterialEditorDialog",
    "PrepareModelDialog",
    "DefeaturingDialog",
    "DisplayOptionsDialog",
    "DisplayParametersSettingsDialog",
    "RadiationParamsDialog",
    "ThermalModelExportDialog",
    "PostProcessingDialog",
    "SubdivideSurfaceDialog",
    "OrbitEnvironmentDialog",
    "load_tle_presets",
    "save_tle_presets",
    "OrbitStepDialog",
]
